version: 2
jobs:
  build:
    docker:
      - image: registry.videolan.org:5000/vlc-debian-android:latest
    working_directory: ~/vlc-android-sdk
    steps:
      - run: echo 'export ANDROID_HOME=/sdk/android-sdk-linux' >> $BASH_ENV
      - run: echo 'export ANDROID_NDK=/sdk/android-ndk' >> $BASH_ENV
      - run: echo 'export ANDROID_SDK=$ANDROID_HOME' >> $BASH_ENV
      - checkout
#      - run:
#          name: Install packages
#          command: ./config/circleci/install-packages.sh
      - run:
          name: Install SDK
          command: ./config/circleci/install-sdk.sh
      - run:
          name: Clone repos
          command: ./config/circleci/clone-repos.sh
      - run:
          name: Compile
          command: ./config/circleci/run-tests.sh
      - run:
          name: Deploy
          command: ./config/circleci/deploy.sh

