version: 2
jobs:
  build:
    docker:
      - image: butterproject/vlc-android:latest
    working_directory: ~/vlc-android-sdk
    steps:
      - run: echo 'export ANDROID_HOME=/sdk/android-sdk-linux' >> $BASH_ENV
      - run: echo 'export ANDROID_NDK=/sdk/android-ndk' >> $BASH_ENV
      - run: echo 'export ANDROID_SDK=$ANDROID_HOME' >> $BASH_ENV
      - checkout
      - run:
          name: Clone repos
          command: ./config/circleci/clone-repos.sh
      - run:
          name: Compile
          command: ./config/circleci/compile-vlc.sh
      - store_artifacts:
          path: ~/vlc-android-sdk/build/outputs/aar/vlc-android-sdk-debug.aar
      - run:
          name: Deploy
          command: ./config/circleci/deploy.sh

