version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:zesty
    working_directory: ~/vlc-android-sdk
    steps:
      - checkout
      - run:
          name: Execute all
          command: ./config/run-tests.sh

#machine:
#  java:
#    version: oraclejdk8
#
#dependencies:
#  pre:
#    - mkdir $HOME/android-sdk
#    - export ANDROID_HOME=$HOME/android-sdk
#    - export ANDROID_NDK=$ANDROID_HOME/android-ndk-r14b
#    - export ANDROID_SDK=$ANDROID_HOME
#    - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
#    - unzip -o sdk-tools-linux-3859397.zip -d $ANDROID_HOME/
#    - wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip
#    - unzip -o android-ndk-r14b-linux-x86_64.zip -d $ANDROID_HOME/
#    - mv $ANDROID_NDK/android-ndk-r14b/* $ANDROID_NDK/
#    - mkdir "$ANDROID_SDK/licenses"
#    - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
#    - echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"
#    - git clone https://code.videolan.org/videolan/vlc-android.git vlc-android
#    - cd vlc-android
#    - git checkout 2.1.15
#    - git clone http://git.videolan.org/git/vlc.git vlc
#    - cd vlc
#    - git checkout bdb4031
#    - cd ../..
#    - $ANDROID_SDK/tools/bin/sdkmanager "platforms;android-26"
#    - ./gradlew vlcBuild
#
##    - if ! $(grep -q "Revision=41.0.0" $ANDROID_HOME/extras/android/m2repository/source.properties); then echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"; fi
##    - if ! $(grep -q "Revision=25.2.4" $ANDROID_HOME/tools/source.properties); then echo y | android update sdk --no-ui --all --filter "tools"; fi
##    - if ! $(grep -q "Revision=25.0.2" $ANDROID_HOME/platform-tools/source.properties); then echo y | android update sdk --no-ui --all --filter "platform-tools"; fi
##    - if [ ! -e $ANDROID_HOME/platforms/android-24 ]; then echo y | android update sdk --no-ui --all --filter "android-24"; fi
##    - if [ ! -e $ANDROID_HOME/build-tools/24.0.2 ]; then echo y | android update sdk --no-ui --all --filter "build-tools-24.0.2"; fi
##  cache_directories:
##    - /usr/local/android-sdk-linux/extras/android/m2repository
##    - /usr/local/android-sdk-linux/tools
##    - /usr/local/android-sdk-linux/platform-tools
##    - /usr/local/android-sdk-linux/platforms/android-24
##    - /usr/local/android-sdk-linux/build-tools/24.0.2
#
#test:
#  override:
#    - config/circleci/run-tests.sh:
#        parallel: true
#
#deployment:
#  production:
#    branch: master
#    commands:
#      - ./gradlew bintrayUpload
